// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhCGPDrppP4Q8tsdtl7WU8AD-OWwWb9g',
    appId: '1:583187854648:web:b6ba7cab314107bac33dcd',
    messagingSenderId: '583187854648',
    projectId: 'portalapp-feb06',
    authDomain: 'portalapp-feb06.firebaseapp.com',
    storageBucket: 'portalapp-feb06.appspot.com',
    measurementId: 'G-J7KXLJNR89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArkKB6gHCmxrfDTsMu45jaF-V6uuGSDLQ',
    appId: '1:583187854648:android:4d378c58443655cec33dcd',
    messagingSenderId: '583187854648',
    projectId: 'portalapp-feb06',
    storageBucket: 'portalapp-feb06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdpKQMQlz_iL4Gt-ZYfoZVgQJOemwHlz4',
    appId: '1:583187854648:ios:d0c2af9db2d37ca9c33dcd',
    messagingSenderId: '583187854648',
    projectId: 'portalapp-feb06',
    storageBucket: 'portalapp-feb06.appspot.com',
    iosBundleId: 'com.example.portalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdpKQMQlz_iL4Gt-ZYfoZVgQJOemwHlz4',
    appId: '1:583187854648:ios:c6ca3497fda55392c33dcd',
    messagingSenderId: '583187854648',
    projectId: 'portalapp-feb06',
    storageBucket: 'portalapp-feb06.appspot.com',
    iosBundleId: 'com.example.portalApp.RunnerTests',
  );
}
